apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: news-replicaset
spec:
  template:
    metadata:
      name: portal-noticias
      labels:
        app: news
    spec:
      containers:
        - name: portal-noticias-container
          image: aluracursos/portal-noticias:1
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: portal-configmap
  replicas: 3
  selector:
    matchLabels:
      app: news